"""agrega tablas de cupones y descuentos

Revision ID: 102f9fd949c4
Revises: da2fd0408c1d
Create Date: 2026-08-10 13:32:16.445040

Cupones de descuento: coupons (PERCENTAGE/FIXED_AMOUNT, scope_type ORDER/CATEGORY/PRODUCT,
ventana de vigencia, topes de uso globales/por cliente, first_purchase_only) +
coupon_categories/coupon_products (alcance, solo relevantes segun scope_type) +
coupon_assigned_clients ("codigos asignados" - vacia = publico) + coupon_redemptions
(uso PENDING/CONFIRMED/RELEASED, uno por orden via UniqueConstraint(order_id) - sin
stacking). orders gana coupon_id/coupon_code/discount_amount/subtotal; carts gana
coupon_code (preview, revalidado en vivo en cada lectura). Ver CLAUDE.md, "Cupones".
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102f9fd949c4'
down_revision: Union[str, Sequence[str], None] = 'da2fd0408c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_total_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_client', sa.Integer(), nullable=True),
    sa.Column('first_purchase_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_index(op.f('ix_coupons_uuid'), 'coupons', ['uuid'], unique=True)
    op.create_table('coupon_assigned_clients',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'client_account_id')
    )
    op.create_table('coupon_categories',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('category_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_uuid'], ['categories.uuid'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'category_uuid')
    )
    op.create_table('coupon_products',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'product_id')
    )
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='ux_coupon_redemptions_order_id')
    )
    op.create_index(op.f('ix_coupon_redemptions_client_account_id'), 'coupon_redemptions', ['client_account_id'], unique=False)
    op.create_index('ix_coupon_redemptions_coupon_client_status', 'coupon_redemptions', ['coupon_id', 'client_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index('ix_coupon_redemptions_coupon_status', 'coupon_redemptions', ['coupon_id', 'status'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_id'), 'coupon_redemptions', ['id'], unique=False)
    op.add_column('carts', sa.Column('coupon_code', sa.String(), nullable=True))
    # ix_order_idempotency_keys_id omitido: drift preexistente no relacionado con este
    # cambio (autogenerate lo detecto de paso), fuera de alcance aqui - mismo precedente
    # que da2fd0408c1d/d546a205a4be.
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key('fk_orders_coupon_id_coupons', 'orders', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_coupon_id_coupons', 'orders', type_='foreignkey')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'coupon_id')
    op.drop_column('carts', 'coupon_code')
    op.drop_index(op.f('ix_coupon_redemptions_id'), table_name='coupon_redemptions')
    op.drop_index('ix_coupon_redemptions_coupon_status', table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_index('ix_coupon_redemptions_coupon_client_status', table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_client_account_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_table('coupon_products')
    op.drop_table('coupon_categories')
    op.drop_table('coupon_assigned_clients')
    op.drop_index(op.f('ix_coupons_uuid'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
