"""agrega tabla de carritos de compra

Revision ID: 10476be01604
Revises: 9838c19e3da0
Create Date: 2026-07-18 08:33:03.334203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10476be01604'
down_revision: Union[str, Sequence[str], None] = '9838c19e3da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_client_account_id'), 'carts', ['client_account_id'], unique=True)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_index(op.f('ix_carts_uuid'), 'carts', ['uuid'], unique=True)
    # ### end Alembic commands ###
    # NOTA: autogenerate tambien detecta un drop de ix_products_name_trgm/ix_products_sku_trgm
    # como falso positivo (son indices GIN creados con SQL crudo en 224799e4444b; Alembic no
    # los reconoce via reflexion normal). Eliminado a proposito de este archivo - no tocar esos indices aqui.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carts_uuid'), table_name='carts')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_client_account_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
