"""Agrega additional skus corregido

Revision ID: 17b35b1cc430
Revises: 92e7b20701aa
Create Date: 2026-07-01 09:36:40.160673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b35b1cc430'
down_revision: Union[str, Sequence[str], None] = '92e7b20701aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_skus', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('additional_images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('sales_unit_uuid', sa.String(), nullable=True))
    op.add_column('products', sa.Column('details_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'details_updated_at')
    op.drop_column('products', 'sales_unit_uuid')
    op.drop_column('products', 'additional_images')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'additional_skus')
    # ### end Alembic commands ###
