"""agrega outbox de sincronizacion con sicar y soft-delete a orders

Revision ID: 2ca3569d7cc3
Revises: 7da0e13dcb05
Create Date: 2026-07-28 13:32:29.751277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca3569d7cc3'
down_revision: Union[str, Sequence[str], None] = '7da0e13dcb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sicar_sync_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('cash_register_uuid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sicar_sync_outbox_id'), 'sicar_sync_outbox', ['id'], unique=False)
    op.create_index('ix_sicar_sync_outbox_one_pending_per_order_action', 'sicar_sync_outbox', ['order_id', 'action'], unique=True, postgresql_where=sa.text("status in ('PENDING', 'IN_PROGRESS')"))
    op.create_index('ix_sicar_sync_outbox_order_id', 'sicar_sync_outbox', ['order_id'], unique=False)
    op.create_index('ix_sicar_sync_outbox_status_next_attempt_at', 'sicar_sync_outbox', ['status', 'next_attempt_at'], unique=False)
    op.add_column('orders', sa.Column('sicar_document_uuid', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'deleted_at')
    op.drop_column('orders', 'sicar_document_uuid')
    op.drop_index('ix_sicar_sync_outbox_status_next_attempt_at', table_name='sicar_sync_outbox')
    op.drop_index('ix_sicar_sync_outbox_order_id', table_name='sicar_sync_outbox')
    op.drop_index('ix_sicar_sync_outbox_one_pending_per_order_action', table_name='sicar_sync_outbox', postgresql_where=sa.text("status in ('PENDING', 'IN_PROGRESS')"))
    op.drop_index(op.f('ix_sicar_sync_outbox_id'), table_name='sicar_sync_outbox')
    op.drop_table('sicar_sync_outbox')
    # ### end Alembic commands ###
