"""Agrega is_deleted para no mostrar productos en la base de datos local que ya no existen en SICAR

Revision ID: 2fb1e8d7d569
Revises: 17b35b1cc430
Create Date: 2026-07-02 18:01:28.848654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb1e8d7d569'
down_revision: Union[str, Sequence[str], None] = '17b35b1cc430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
