"""add product attributes presets and variant groups

Revision ID: 418f7e68c49e
Revises: 9442999722db
Create Date: 2026-08-04 17:08:17.790714

Slice de "Product Attributes" (ver CLAUDE.md) - NO la taxonomia N1-N5 propuesta
originalmente (esa fue descartada: `categories`/`vehicles` ya cubren eso). Hibrido:
`attributes` es solo un catalogo de definiciones (nombre/slug/data_type/unit); los
VALORES reales de cada producto viven en `products.attributes` (JSONB, GIN
`jsonb_path_ops`, mismo patron que `products.tags`) - no una tabla EAV por fila.
`attribute_presets`/`attribute_preset_items` son bundles de conveniencia para
admin/bulk-import, nunca obligatorios ni validados contra un producto. `variant_groups`
vincula SKUs de Sicar X distintos que son la misma pieza en variantes (color/talla) -
curado a mano, sin inferencia automatica (SKUs de proveedores demasiado inconsistentes
para agrupar con confianza). Todas las tablas nuevas empiezan vacias; `products.attributes`/
`products.variant_group_uuid` empiezan NULL en las ~90k filas existentes - sin backfill.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '418f7e68c49e'
down_revision: Union[str, Sequence[str], None] = '9442999722db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_presets',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('attributes',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('variant_groups',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('variant_attribute_slug', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('attribute_preset_items',
    sa.Column('preset_uuid', sa.String(), nullable=False),
    sa.Column('attribute_uuid', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_uuid'], ['attributes.uuid'], ),
    sa.ForeignKeyConstraint(['preset_uuid'], ['attribute_presets.uuid'], ),
    sa.PrimaryKeyConstraint('preset_uuid', 'attribute_uuid')
    )
    op.create_index('ix_attribute_preset_items_attribute_uuid', 'attribute_preset_items', ['attribute_uuid'], unique=False)
    # ix_order_idempotency_keys_id omitido a proposito: ya cubierto por la PK (falso positivo recurrente de autogenerate, ver 52ccc4e9556e).
    op.add_column('products', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('variant_group_uuid', sa.String(), nullable=True))
    op.create_index('ix_products_attributes_gin', 'products', ['attributes'], unique=False, postgresql_using='gin', postgresql_ops={'attributes': 'jsonb_path_ops'})
    op.create_index(op.f('ix_products_variant_group_uuid'), 'products', ['variant_group_uuid'], unique=False)
    op.create_foreign_key('fk_products_variant_group_uuid', 'products', 'variant_groups', ['variant_group_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_variant_group_uuid', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_variant_group_uuid'), table_name='products')
    op.drop_index('ix_products_attributes_gin', table_name='products', postgresql_using='gin', postgresql_ops={'attributes': 'jsonb_path_ops'})
    op.drop_column('products', 'variant_group_uuid')
    op.drop_column('products', 'attributes')
    op.drop_index('ix_attribute_preset_items_attribute_uuid', table_name='attribute_preset_items')
    op.drop_table('attribute_preset_items')
    op.drop_table('variant_groups')
    op.drop_table('attributes')
    op.drop_table('attribute_presets')
    # ### end Alembic commands ###
