"""add mercado pago payment fields to orders

Revision ID: 44f0460ccffc
Revises: 10476be01604
Create Date: 2026-07-20 11:48:16.040060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f0460ccffc'
down_revision: Union[str, Sequence[str], None] = '10476be01604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('mp_payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('mp_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('mp_status_detail', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('mp_payment_method_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('mp_ticket_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_mp_payment_id'), 'orders', ['mp_payment_id'], unique=True)
    # NOTA: autogenerate tambien detecto los indices GIN de pg_trgm (ix_products_sku_trgm,
    # ix_products_name_trgm) como "removidos" -- falso positivo ya documentado en la
    # migracion d8ca048fb64d (no estan declarados en el modelo Product), removido de aqui.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_mp_payment_id'), table_name='orders')
    op.drop_column('orders', 'mp_ticket_url')
    op.drop_column('orders', 'mp_payment_method_id')
    op.drop_column('orders', 'mp_status_detail')
    op.drop_column('orders', 'mp_status')
    op.drop_column('orders', 'mp_payment_id')
    # ### end Alembic commands ###
