"""agrega tabla de ordenes vinculada a cuentas de cliente

Revision ID: 45f23f03f9ce
Revises: 069dd8677786
Create Date: 2026-07-17 09:16:32.451520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f23f03f9ce'
down_revision: Union[str, Sequence[str], None] = '069dd8677786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('sicar_order_id', sa.String(), nullable=False),
    sa.Column('serie_folio', sa.String(), nullable=True),
    sa.Column('sicar_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_info', sa.JSON(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_account_id'), 'orders', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_sicar_order_id'), 'orders', ['sicar_order_id'], unique=True)
    op.create_index(op.f('ix_orders_uuid'), 'orders', ['uuid'], unique=True)
    # ### end Alembic commands ###
    # NOTA: autogenerate tambien detecta un drop de ix_products_name_trgm/ix_products_sku_trgm
    # como falso positivo (son indices GIN creados con SQL crudo en 224799e4444b; Alembic no
    # los reconoce via reflexion normal). Eliminado a proposito de este archivo - no tocar esos indices aqui.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_uuid'), table_name='orders')
    op.drop_index(op.f('ix_orders_sicar_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_account_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
