"""add vehicles and product_vehicles tables

Revision ID: 52ccc4e9556e
Revises: 56842c6e8af0
Create Date: 2026-08-01 10:33:59.521504

Vehicle compatibility PIM slice (see CLAUDE.md, "Compatibilidad de vehiculos") - a flat
`vehicles` table (make/model/year_start/year_end/engine, no self-reference/tree - a
fitment row isn't a hierarchy, unlike `categories`) plus `product_vehicles` (N:M,
product<->vehicle), mirroring `product_categories` exactly. Both start empty - admin
CRUD is `/v1/admin/vehicles/*`; `vehicles` can optionally be seeded from a one-off
script (`import_gonher_vehicles.py`), never `product_vehicles`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ccc4e9556e'
down_revision: Union[str, Sequence[str], None] = '56842c6e8af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_vehicles_type_make_model', 'vehicles', ['vehicle_type', 'make', 'model'], unique=False)
    op.create_table('product_vehicles',
    sa.Column('vehicle_uuid', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vehicle_uuid'], ['vehicles.uuid'], ),
    sa.PrimaryKeyConstraint('vehicle_uuid', 'product_id')
    )
    op.create_index('ix_product_vehicles_product_id', 'product_vehicles', ['product_id'], unique=False)
    # ### end Alembic commands ###
    # ix_order_idempotency_keys_id omitted on purpose: already covered by the PK.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_vehicles_product_id', table_name='product_vehicles')
    op.drop_table('product_vehicles')
    op.drop_index('ix_vehicles_type_make_model', table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
