"""agrega uuid a direcciones y restriccion de una default por cliente

Revision ID: 56c152338087
Revises: d8ca048fb64d
Create Date: 2026-07-16 18:31:05.686264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c152338087'
down_revision: Union[str, Sequence[str], None] = 'd8ca048fb64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfillea uuids unicos si la tabla ya tiene filas (gen_random_uuid()
    # esta disponible en Postgres 16 sin necesidad de extension); se quita despues de
    # crear la columna, ya que el valor por-fila real lo sigue generando el modelo (uuid4()).
    op.add_column('client_addresses', sa.Column('uuid', sa.String(), nullable=False, server_default=sa.text('gen_random_uuid()::text')))
    op.alter_column('client_addresses', 'uuid', server_default=None)
    op.create_index('ix_client_addresses_one_default', 'client_addresses', ['client_account_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_index(op.f('ix_client_addresses_uuid'), 'client_addresses', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_addresses_uuid'), table_name='client_addresses')
    op.drop_index('ix_client_addresses_one_default', table_name='client_addresses', postgresql_where=sa.text('is_default = true'))
    op.drop_column('client_addresses', 'uuid')
    # ### end Alembic commands ###
