"""Agrega eliminated_at para calcular el tiempo de eliminado de un producto

Revision ID: 622fd2c71cb5
Revises: 2fb1e8d7d569
Create Date: 2026-07-03 11:24:36.460546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622fd2c71cb5'
down_revision: Union[str, Sequence[str], None] = '2fb1e8d7d569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('eliminated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'eliminated_at')
    # ### end Alembic commands ###
