"""agrega delivery_cost a orders y county a client_addresses

Revision ID: 6702e8cd3eba
Revises: 44f0460ccffc
Create Date: 2026-07-21 09:24:20.980796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6702e8cd3eba'
down_revision: Union[str, Sequence[str], None] = '44f0460ccffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_addresses', sa.Column('county', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # Drop de ix_products_*_trgm omitido: falso positivo (ver d8ca048fb64d/ad4e748fca2d).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_cost')
    op.drop_column('client_addresses', 'county')
    # ### end Alembic commands ###
