"""Agrega las columnas para datos cambiantes basados en fecha de actualización

Revision ID: 92e7b20701aa
Revises: 4716222a75ee
Create Date: 2026-07-01 09:00:48.501686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e7b20701aa'
down_revision: Union[str, Sequence[str], None] = '4716222a75ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
