"""Cambia el nombre de eliminated_at a deleted_at

Revision ID: 96fc6a46566a
Revises: 622fd2c71cb5
Create Date: 2026-07-06 10:29:22.700015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96fc6a46566a'
down_revision: Union[str, Sequence[str], None] = '622fd2c71cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('products', 'eliminated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('eliminated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('products', 'deleted_at')
    # ### end Alembic commands ###
