"""agrega dispatch_status y dispatch_history a ordenes

Revision ID: 9838c19e3da0
Revises: 45f23f03f9ce
Create Date: 2026-07-17 09:29:58.049901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9838c19e3da0'
down_revision: Union[str, Sequence[str], None] = '45f23f03f9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('dispatch_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('dispatch_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
    # NOTA: autogenerate tambien detecta un drop de ix_products_name_trgm/ix_products_sku_trgm
    # como falso positivo (indices GIN creados con SQL crudo en 224799e4444b) - eliminado a
    # proposito, ver la misma nota en 45f23f03f9ce.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'dispatch_history')
    op.drop_column('orders', 'dispatch_status')
    # ### end Alembic commands ###
