"""Se agrega la columna last_sync_id para realizar eliminaciones de forma más eficiente

Revision ID: a21fd33fb088
Revises: 5f0bdc84fead
Create Date: 2026-07-06 16:11:20.221302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21fd33fb088'
down_revision: Union[str, Sequence[str], None] = '5f0bdc84fead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('last_sync_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_last_sync_id'), 'products', ['last_sync_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_last_sync_id'), table_name='products')
    op.drop_column('products', 'last_sync_id')
    # ### end Alembic commands ###
