"""agrega tablas de cuentas de cliente y direcciones

Revision ID: ad4e748fca2d
Revises: 6854715fa27b
Create Date: 2026-07-16 17:41:39.309688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4e748fca2d'
down_revision: Union[str, Sequence[str], None] = '6854715fa27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_accounts_email'), 'client_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_client_accounts_id'), 'client_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_client_accounts_uuid'), 'client_accounts', ['uuid'], unique=True)
    op.create_table('client_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('ext_number', sa.String(), nullable=True),
    sa.Column('int_number', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_addresses_client_account_id'), 'client_addresses', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_client_addresses_id'), 'client_addresses', ['id'], unique=False)
    # NOTA: autogenerate detecta los indices GIN de pg_trgm (ix_products_name_trgm /
    # ix_products_sku_trgm) como "removidos" porque no estan declarados en el modelo
    # Product (se crearon con SQL crudo en 224799e4444b) — falso positivo, no tocarlos.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_addresses_id'), table_name='client_addresses')
    op.drop_index(op.f('ix_client_addresses_client_account_id'), table_name='client_addresses')
    op.drop_table('client_addresses')
    op.drop_index(op.f('ix_client_accounts_uuid'), table_name='client_accounts')
    op.drop_index(op.f('ix_client_accounts_id'), table_name='client_accounts')
    op.drop_index(op.f('ix_client_accounts_email'), table_name='client_accounts')
    op.drop_table('client_accounts')
    # ### end Alembic commands ###
