"""agrega latitude y longitude a client_addresses

Revision ID: bda8078263da
Revises: 6702e8cd3eba
Create Date: 2026-07-21 13:15:46.801944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda8078263da'
down_revision: Union[str, Sequence[str], None] = '6702e8cd3eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('client_addresses', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_products_name_trgm'), table_name='products', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_sku_trgm'), table_name='products', postgresql_ops={'sku': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_sku_trgm'), 'products', ['sku'], unique=False, postgresql_ops={'sku': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_products_name_trgm'), 'products', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('client_addresses', 'longitude')
    op.drop_column('client_addresses', 'latitude')
    # ### end Alembic commands ###
