"""add order accept and delivery assignment fields, add sync_status table

Revision ID: d258e6f72a3a
Revises: 2ca3569d7cc3
Create Date: 2026-07-29 09:07:23.442793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd258e6f72a3a'
down_revision: Union[str, Sequence[str], None] = '2ca3569d7cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('products_processed', sa.Integer(), nullable=True),
    sa.Column('products_deactivated', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: autogenerate tambien detecto 'ix_order_idempotency_keys_id' como faltante (drift
    # preexistente y no relacionado - OrderIdempotencyKey.id ya tiene index=True en el modelo
    # pero la migracion original que creo la tabla nunca genero ese indice). Se omite
    # deliberadamente aqui para que esta migracion se quede enfocada en accept/delivery/
    # sync_status - si se quiere corregir ese drift, que sea su propia migracion aparte.
    op.add_column('orders', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('accepted_by', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_company', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_assigned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_assigned_at')
    op.drop_column('orders', 'delivery_company')
    op.drop_column('orders', 'accepted_by')
    op.drop_column('orders', 'accepted_at')
    op.drop_table('sync_status')
    # ### end Alembic commands ###
