"""Add country column to ClientAddress

Revision ID: d8ca048fb64d
Revises: ad4e748fca2d
Create Date: 2026-07-16 17:51:53.403274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ca048fb64d'
down_revision: Union[str, Sequence[str], None] = 'ad4e748fca2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_addresses', sa.Column('country', sa.String(), nullable=True))
    # NOTA: autogenerate detecta los indices GIN de pg_trgm como "removidos" porque no
    # estan declarados en el modelo Product — falso positivo, no tocarlos (ver ad4e748fca2d).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_addresses', 'country')
    # ### end Alembic commands ###
