"""agrega tabla de resenas de productos

Revision ID: da2fd0408c1d
Revises: d546a205a4be
Create Date: 2026-08-10 08:47:56.032486

Agrega reseñas y calificaciones de productos: product_reviews (rating 1-5 + comentario
opcional, una por cliente por producto via UniqueConstraint, moderacion admin via
is_hidden/hidden_reason, respuesta oficial inline via admin_reply/admin_reply_at) y
product_review_helpful_votes (un voto "util" por cliente por reseña, toggleable).
products gana average_rating/reviews_count, cacheados y mantenidos exclusivamente por
review_service.recompute_product_rating (excluidos del upsert de sync_task.py, igual
que sales_count/reserved - ver CLAUDE.md, "Reserva local de stock").
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2fd0408c1d'
down_revision: Union[str, Sequence[str], None] = 'd546a205a4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('hidden_reason', sa.String(), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('admin_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_product_reviews_rating_range'),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'client_account_id', name='ux_product_reviews_product_client')
    )
    op.create_index(op.f('ix_product_reviews_client_account_id'), 'product_reviews', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_id'), 'product_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_uuid'), 'product_reviews', ['uuid'], unique=True)
    op.create_table('product_review_helpful_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['product_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'client_account_id', name='ux_review_helpful_votes_review_client')
    )
    op.create_index(op.f('ix_product_review_helpful_votes_client_account_id'), 'product_review_helpful_votes', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_product_review_helpful_votes_id'), 'product_review_helpful_votes', ['id'], unique=False)
    op.create_index(op.f('ix_product_review_helpful_votes_review_id'), 'product_review_helpful_votes', ['review_id'], unique=False)
    # Drop/create de ix_order_idempotency_keys_id omitido: drift preexistente no
    # relacionado con este cambio (autogenerate lo detecto de paso), fuera de alcance aqui
    # - mismo precedente que d546a205a4be.
    op.add_column('products', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'average_rating')
    op.drop_index(op.f('ix_product_review_helpful_votes_review_id'), table_name='product_review_helpful_votes')
    op.drop_index(op.f('ix_product_review_helpful_votes_id'), table_name='product_review_helpful_votes')
    op.drop_index(op.f('ix_product_review_helpful_votes_client_account_id'), table_name='product_review_helpful_votes')
    op.drop_table('product_review_helpful_votes')
    op.drop_index(op.f('ix_product_reviews_uuid'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_client_account_id'), table_name='product_reviews')
    op.drop_table('product_reviews')
    # ### end Alembic commands ###
