"""Agrega tablas de departamentos y categorias

Revision ID: efb3b56c3a03
Revises: a21fd33fb088
Create Date: 2026-07-11 12:04:51.261817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb3b56c3a03'
down_revision: Union[str, Sequence[str], None] = 'a21fd33fb088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('departments',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('department_category',
    sa.Column('department_uuid', sa.String(), nullable=False),
    sa.Column('category_uuid', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_uuid'], ['categories.uuid'], ),
    sa.ForeignKeyConstraint(['department_uuid'], ['departments.uuid'], ),
    sa.PrimaryKeyConstraint('department_uuid', 'category_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_category')
    op.drop_table('departments')
    op.drop_table('categories')
    # ### end Alembic commands ###
