"""Agregar precios de mayoreo

Revision ID: f11518ceb839
Revises: c77b3e6b1d24
Create Date: 2026-06-30 13:25:22.366733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11518ceb839'
down_revision: Union[str, Sequence[str], None] = 'c77b3e6b1d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price2', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('price3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price3')
    op.drop_column('products', 'price2')
    # ### end Alembic commands ###
